//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package manual2v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeerConnectionAccepter) DeepCopyInto(out *VPCPeerConnectionAccepter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeerConnectionAccepter.
func (in *VPCPeerConnectionAccepter) DeepCopy() *VPCPeerConnectionAccepter {
	if in == nil {
		return nil
	}
	out := new(VPCPeerConnectionAccepter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCPeerConnectionAccepter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeerConnectionAccepterList) DeepCopyInto(out *VPCPeerConnectionAccepterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCPeerConnectionAccepter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeerConnectionAccepterList.
func (in *VPCPeerConnectionAccepterList) DeepCopy() *VPCPeerConnectionAccepterList {
	if in == nil {
		return nil
	}
	out := new(VPCPeerConnectionAccepterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCPeerConnectionAccepterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeerConnectionAccepterObservation) DeepCopyInto(out *VPCPeerConnectionAccepterObservation) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeerConnectionAccepterObservation.
func (in *VPCPeerConnectionAccepterObservation) DeepCopy() *VPCPeerConnectionAccepterObservation {
	if in == nil {
		return nil
	}
	out := new(VPCPeerConnectionAccepterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeerConnectionAccepterParameters) DeepCopyInto(out *VPCPeerConnectionAccepterParameters) {
	*out = *in
	if in.VPCPeeringConnectionID != nil {
		in, out := &in.VPCPeeringConnectionID, &out.VPCPeeringConnectionID
		*out = new(string)
		**out = **in
	}
	if in.VPCPeeringConnectionIDRef != nil {
		in, out := &in.VPCPeeringConnectionIDRef, &out.VPCPeeringConnectionIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCPeeringConnectionIDSelector != nil {
		in, out := &in.VPCPeeringConnectionIDSelector, &out.VPCPeeringConnectionIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeerConnectionAccepterParameters.
func (in *VPCPeerConnectionAccepterParameters) DeepCopy() *VPCPeerConnectionAccepterParameters {
	if in == nil {
		return nil
	}
	out := new(VPCPeerConnectionAccepterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeerConnectionAccepterSpec) DeepCopyInto(out *VPCPeerConnectionAccepterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeerConnectionAccepterSpec.
func (in *VPCPeerConnectionAccepterSpec) DeepCopy() *VPCPeerConnectionAccepterSpec {
	if in == nil {
		return nil
	}
	out := new(VPCPeerConnectionAccepterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCPeerConnectionAccepterStatus) DeepCopyInto(out *VPCPeerConnectionAccepterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCPeerConnectionAccepterStatus.
func (in *VPCPeerConnectionAccepterStatus) DeepCopy() *VPCPeerConnectionAccepterStatus {
	if in == nil {
		return nil
	}
	out := new(VPCPeerConnectionAccepterStatus)
	in.DeepCopyInto(out)
	return out
}
