/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActionCode string

const (
	ActionCode_ArchiveRetrieval   ActionCode = "ArchiveRetrieval"
	ActionCode_InventoryRetrieval ActionCode = "InventoryRetrieval"
	ActionCode_Select             ActionCode = "Select"
)

type CannedACL string

const (
	CannedACL_private                   CannedACL = "private"
	CannedACL_public_read               CannedACL = "public-read"
	CannedACL_public_read_write         CannedACL = "public-read-write"
	CannedACL_aws_exec_read             CannedACL = "aws-exec-read"
	CannedACL_authenticated_read        CannedACL = "authenticated-read"
	CannedACL_bucket_owner_read         CannedACL = "bucket-owner-read"
	CannedACL_bucket_owner_full_control CannedACL = "bucket-owner-full-control"
)

type EncryptionType string

const (
	EncryptionType_aws_kms EncryptionType = "aws:kms"
	EncryptionType_AES256  EncryptionType = "AES256"
)

type ExpressionType string

const (
	ExpressionType_SQL ExpressionType = "SQL"
)

type FileHeaderInfo string

const (
	FileHeaderInfo_USE    FileHeaderInfo = "USE"
	FileHeaderInfo_IGNORE FileHeaderInfo = "IGNORE"
	FileHeaderInfo_NONE   FileHeaderInfo = "NONE"
)

type Permission string

const (
	Permission_FULL_CONTROL Permission = "FULL_CONTROL"
	Permission_WRITE        Permission = "WRITE"
	Permission_WRITE_ACP    Permission = "WRITE_ACP"
	Permission_READ         Permission = "READ"
	Permission_READ_ACP     Permission = "READ_ACP"
)

type QuoteFields string

const (
	QuoteFields_ALWAYS   QuoteFields = "ALWAYS"
	QuoteFields_ASNEEDED QuoteFields = "ASNEEDED"
)

type StatusCode string

const (
	StatusCode_InProgress StatusCode = "InProgress"
	StatusCode_Succeeded  StatusCode = "Succeeded"
	StatusCode_Failed     StatusCode = "Failed"
)

type StorageClass string

const (
	StorageClass_STANDARD           StorageClass = "STANDARD"
	StorageClass_REDUCED_REDUNDANCY StorageClass = "REDUCED_REDUNDANCY"
	StorageClass_STANDARD_IA        StorageClass = "STANDARD_IA"
)

type Type string

const (
	Type_AmazonCustomerByEmail Type = "AmazonCustomerByEmail"
	Type_CanonicalUser         Type = "CanonicalUser"
	Type_Group                 Type = "Group"
)
